#!/usr/bin/env python
# Andrew Borgman
# Use average recombination rate across dog genome to create
# map files for XPEHH calculations
# The average cm/Mb ratio is 0.97 across the genome, so use the 
# Mb distance as a proxy for the cM distance in an initial scan.
import os,sys

# Storage
MAP_DIR = "/home/andrew/point/hap_analysis/map_files/"

# Grabbing SNP order
map_data = []
with open("/share/canFam3.map") as map_file:
	for line in map_file:
		spl = line.replace("\n", "").split()
		if spl[0] == 'X' or spl[0] == 'Y':
			spl[0] = 39
		tup = [spl[1], int(spl[0]), int(spl[3])]
		map_data.append(tup)

map_data = sorted(map_data, key=itemgetter(1,2))

# Write out map files to ./map subdirectory in xpehh analysis folder
#  SNP		  BP     CM POS  
# rs17054921 13043 0.0126517 A C
